config/routes.rb
TestUploadify::Application.routes.draw do
  resources :pictures  do
    collection do
      get 'get_thumb'
    end
  end

  root :to => 'pictures#index'

end

app/models/picture.rb
# -*- encoding : utf-8 -*-

class Picture < ActiveRecord::Base
  
  attr_accessible :image

  mount_uploader :image, ImageUploader

end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pictures_controller.rb
# -*- encoding : utf-8 -*-
#encoding: utf-8

class PicturesController < ApplicationController


protect_from_forgery :except => :create

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @picture = Picture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    @picture = Picture.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create

    newparams = coerce(params)
    # @upload = Upload.new(newparams[:upload])

    # p_attr = []
    
    # p_attr[:image] = params[:Filedata][:filename].first if params[:Filedata][:filename].class == Array
    # p_attr = params[:Filename].to_s


    # @picture = Picture.new(:image => 'paris.jpg')
    # newparams[:picture][:image].inspect

    # image_filename = URI.unescape(newparams[:picture][:image])
    # @picture = Picture.new(URI.unescape(newparams[:picture]))

    @picture = Picture.new(newparams[:picture])

    respond_to do |format|
      if @picture.save
        # format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        # format.js { @picture.id }
        return  true
      else
        format.html { render action: "new" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update
    @picture = Picture.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end

  def get_thumb
    # temp_filename = params[:file]
    # filename = string = CGI::unescape(temp_filename)
    file = Picture.find_by_image(params[:file])
    respond_to do |format|
        format.json { render json: {:id => file.id, :thumb => file.image.thumb.url} }
    end    
  end

  private 
  def coerce(params)
    if params[:picture].nil? 
      h = Hash.new 
      h[:picture] = Hash.new       
      h[:picture][:image] = params[:Filedata] 
      # h[:picture][:image].content_type = MIME::Types.type_for(h[:picture][:image].original_filename).to_s
      h
    else 
      params
    end 
  end

end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
end

app/helpers/pictures_helper.rb
# -*- encoding : utf-8 -*-
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestUploadify</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <div class="row">
      <div class="span7">
        <%= yield %>
      </div>
      
    </div>
  </div>

</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for @picture, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :image, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :image, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                pictures_path, :class => 'btn' %>
  </div>
<% end %>

app/views/pictures/create.js.erb
arert("From server");

app/views/pictures/edit.html.erb
<%- model_class = @picture.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/pictures/index.html.erb
<%= form_for Picture.new, :html => {:multipart => true} do |f| %> 
 
<p>
  <%= f.file_field :photo, :id => "uploadify"%> </p>
  
<% end %>
<script>
<% key = Rails.application.config.session_options[:key] %>
  var uploadify_script_data = {};
  var csrf_param = $('meta[name=csrf-param]').attr('content');
  var csrf_token = $('meta[name=csrf-token]').attr('content');
  uploadify_script_data[csrf_param] = encodeURI(encodeURIComponent(csrf_token));
  uploadify_script_data['<%= key %>'] = '<%= cookies[key] %>';
  
  $(document).ready(function() {
  var uploadify_script_data = {};
  $('#uploadify').uploadify({
    swf             : '<%= asset_path("uploadify.swf") %>',
    uploader        : '<%= pictures_path %>',
    // buttonText      : 'Загрузить...',
    buttonCursor    : 'hand',
    height          : 20,
    auto            : true,
    multi           : true,
    removeCompleted : true,
    onUploadComplete : function(file) {
             $.ajax({
                url: "<%= get_thumb_pictures_path %>", 
                dataType: 'json', 
                type: 'get', 
                data: {file: file.name},
                complete: function(json) {
                  var obj = jQuery.parseJSON(json.responseText);
                  var str = '<tr>' +
                              '<td><img src="' + obj.thumb + '"></td>' +
                              '<td style="vertical-align: middle;">' +
                                '<a href="/pictures/' + obj.id + '" class="btn btn-mini" style="margin-right: 5px;">Show</a>' +
                                '<a href="/pictures/' + obj.id + '" class="btn btn-mini btn-danger" data-confirm="Are you sure?" data-method="delete" rel="nofollow">Destroy</a>' +
                              '</td>' +
                            '</tr>';
                  $(str).prependTo($('tbody'));
                  // var obj = jQuery.parseJSON(json.responseText);
                  // console.log(obj.thumb);                               
                }  
              });
    },
    onUploadError : function(file, errorCode, errorMsg, errorString) {
      alert('The file ' + file.name + ' could not be uploaded: ' + errorString);
    },
    formData        : uploadify_script_data
    // onUploadComplete : function(file) {
    //   alert(file);
    // }
  });
});
</script>

<table class="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        
        <td><%= image_tag picture.image.thumb.url %></td>
        <td style="vertical-align: middle;">
          <%= link_to 'Show', picture_path(picture), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      picture_path(picture),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pictures/new.html.erb
<%- model_class = @picture.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/pictures/show.html.erb
<%- model_class = @picture.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= image_tag @picture.image.url %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              pictures_path, :class => 'btn'  %>
  
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              picture_path(@picture),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>